# Generated by Django 3.2 on 2021-04-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_name', models.CharField(max_length=100)),
                ('Title', models.CharField(max_length=100)),
                ('Job_Nature', models.TextField(max_length=250)),
                ('Salary', models.IntegerField()),
                ('No_of_post', models.IntegerField()),
            ],
            options={
                'ordering': ['Company_name'],
            },
        ),
    ]
